import 'package:flutter/material.dart';
import 'brand_config.dart';

class AppLocalization {
  static ValueNotifier<String> currentLanguage = ValueNotifier<String>('en');

  static void toggleLanguage() {
    currentLanguage.value = currentLanguage.value == 'en' ? 'hi' : 'en';
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'AryaSpaces Admin',
      'owner_console': 'Property Owner Console',
      'login': 'Login to Console',
      'phone_number': 'Phone Number',
      'password': 'Password',
      'enter_pin': 'Enter your 6-digit PIN',
      'set_pin': 'Set a 6-digit PIN for fast unlock',
      'confirm_pin': 'Confirm your 6-digit PIN',
      'incorrect_pin': 'Incorrect PIN. Please try again.',
      'pin_mismatch': 'PINs do not match. Try again.',
      'pin_lockout': 'Too many failed attempts. Try again in',
      'commercial': 'Commercial',
      'residential': 'Residential',
      'expected': 'Expected',
      'collected': 'Collected',
      'pending': 'Pending',
      'overdue': 'Overdue',
      'renters': 'Renters & Units',
      'add_renter': 'Add Renter',
      'add_unit': 'Add Unit',
      'pending_confirmations': 'Pending Confirmations',
      'reports': 'Reports & Export',
      'settings': 'Settings',
      'approve': 'Approve Payment',
      'mark_paid': 'Mark Paid Directly',
      'adjust_amount': 'Adjust Amount',
      'export_excel': 'Export Excel Ledger',
      'export_csv': 'Export CSV Data',
      'export_pdf': 'Export Tenant PDF',
      'language': 'Language / भाषा (Hindi)',
      'logout': 'Logout Account',
      'vacant': 'Vacant — Tap to Rent',
      'occupied': 'Occupied',
      'deal_terms': 'Deal Terms',
      'ledger': 'Payment Ledger',
      'agreement': 'Agreement Document',
      'save_deal_terms': 'Save Deal Terms',
      'base_rent': 'Base Monthly Rent (INR)',
      'advance_received': 'Security Advance (INR)',
      'advance_mode': 'Deduct rent from advance balance',
      'advance_months': 'Advance Consumption Period (Months)',
      'rent_schedule': 'Rent Schedule Steps',
      'add_rent_step': '+ Add Rent Change Step',
      'effective_from_month': 'Effective From Month #',
      'rent_due_day': 'Rent Due Day of Month (1-28)',
      'carry_forward': 'Carry forward unpaid balance',
      'reset_login': 'Reset Renter Login',
      'generate_new_password': 'Generate New Login Password',
      'copy_credentials': 'Copy Phone & Password for WhatsApp',
      'edit_property': 'Edit Property Details',
      'drive_link': 'Google Drive Agreement Link',
      'confirm_action': 'Are you sure?',
      'confirm_save_deal': 'Do you want to save these updated deal terms?',
      'yes': 'Yes, Save',
      'cancel': 'Cancel',
      'unit_label': 'Unit Label (e.g. Shop 1 / Flat 101)',
      'floor_level': 'Floor Level',
      'size_sqft': 'Size (Sq. Ft.)',
      'business_name': 'Business / Shop Name',
      'business_cat': 'Business Category (Optional)',
      'occupant_count': 'Number of Occupants',
      'maintenance_included': 'Maintenance included in rent',
      'backup_db': 'Backup / Export Complete Database',
      'reset_pin': 'Reset Security PIN',
      'maintenance_manager': 'Maintenance Tickets Manager',
      'dispatch_notice': 'Post Announcement / Notice',
      'notice_title': 'Notice Title',
      'notice_message': 'Announcement Message',
      'publish_notice': 'Publish Notice to All Tenants',
      'notice_published': 'Notice Broadcasted',
      'dashboard': 'Dashboard Overview',
      'verified_property': 'Verified Direct Property',
      'report_payment': 'Report Payment',
      'payment_history': 'Payment History',
      'deal_summary': 'Deal Summary',
      'maintenance': 'Maintenance',
      'notices': 'Notice Board',
      'report_sent': 'Report Submitted',
      'report_sent_msg': 'Your payment report has been sent to the property owner for verification.',
      'total_due': 'Total Due This Month',
      'amount_paid': 'Amount Paid / Reporting',
      'payment_method': 'Payment Method',
      'upi': 'UPI Transfer',
      'bank': 'Bank Transfer',
      'cash': 'Cash Payment',
      'note_optional': 'Notes / Transaction ID (Optional)',
      'submit_report': 'Submit Payment Report',
      'ok': 'OK',
      'check_for_updates': 'Check for App Updates',
      'checking_updates': 'Checking for updates...',
      'update_available': 'New Version Available',
      'update_now': 'Update Now',
      'later': 'Later',
      'latest_version_msg': 'You are using the latest version!',
      'downloading_update': 'Downloading Update Package...',
      'whats_new': 'What\'s New',
      'mandatory_update': 'Critical Security & Feature Update Required',
      'err_empty_login': 'Please enter both Phone Number and Password.',
      'err_invalid_credentials': 'Incorrect Phone Number or Password. Please check your login details carefully and try again.',
      'err_no_internet': 'No Internet Connection. Please check your Mobile Data or Wi-Fi and try again.',
      'err_too_many_attempts': 'Too many failed login attempts. Please wait 5 minutes and try again.',
      'err_account_disabled': 'Your account is deactivated. Please contact support.',
    },
    'hi': {
      'app_name': 'आर्यास्पेस एडमिन',
      'owner_console': 'प्रॉपर्टी मालिक कंसोल',
      'login': 'लॉगिन करें',
      'phone_number': 'फोन नंबर दर्ज करें',
      'password': 'पासवर्ड',
      'enter_pin': 'अपना 6-अंकीय पिन दर्ज करें',
      'set_pin': 'सुरक्षा के लिए 6-अंकीय पिन बनाएं',
      'confirm_pin': 'पिन की दोबारा पुष्टि करें',
      'incorrect_pin': 'गलत पिन! कृपया पुनः प्रयास करें।',
      'pin_mismatch': 'पिन मेल नहीं खाते।',
      'pin_lockout': 'बहुत अधिक गलत प्रयास। पुनः प्रयास करें',
      'commercial': 'कमर्शियल (दुकानें)',
      'residential': 'रेजिडेंशियल (आवास)',
      'expected': 'अपेक्षित किराया',
      'collected': 'प्राप्त किराया',
      'pending': 'बकाया किराया',
      'overdue': 'अतिदेय (Overdue)',
      'renters': 'किराएदार और इकाइयां',
      'add_renter': 'नया किराएदार जोड़ें',
      'add_unit': 'नई इकाई (दुकान/कमरा) जोड़ें',
      'pending_confirmations': 'पेंडिंग भुगतान पुष्टि',
      'reports': 'रिपोर्ट और हिसाब',
      'settings': 'सेटिंग्स',
      'approve': 'स्वीकार करें (Approve)',
      'mark_paid': 'सीधे जमा अंकित करें (Mark Paid)',
      'adjust_amount': 'राशि बदलें (Adjust)',
      'export_excel': 'एक्सेल फाइल डाउनलोड करें',
      'export_csv': 'CSV डेटा डाउनलोड करें',
      'export_pdf': 'किराएदार PDF रसीद डाउनलोड करें',
      'language': 'भाषा बदलें (English)',
      'logout': 'लॉगआउट',
      'vacant': 'खाली — किराए पर दें',
      'occupied': 'किराए पर दिया हुआ',
      'deal_terms': 'करार और दर की शर्तें',
      'ledger': 'हिसाब-किताब रजिस्टर',
      'agreement': 'किराया नामा दस्तावेज',
      'save_deal_terms': 'शर्तें सेव करें',
      'base_rent': 'मूल मासिक किराया (₹)',
      'advance_received': 'अग्रिम सुरक्षा राशि (₹)',
      'advance_mode': 'किराया अग्रिम जमा राशि से काटें',
      'advance_months': 'अग्रिम समायोजन अवधि (महीने)',
      'rent_schedule': 'किराया शेड्यूल चरण',
      'add_rent_step': '+ किराया परिवर्तन चरण जोड़ें',
      'effective_from_month': 'किस महीने से प्रभावी #',
      'rent_due_day': 'किराया भुगतान की अंतिम तिथि (1-28)',
      'carry_forward': 'बकाया राशि अगले महीने जोड़ें',
      'reset_login': 'किराएदार का लॉगिन रीसेट करें',
      'generate_new_password': 'नया लॉगिन पासवर्ड बनाएं',
      'copy_credentials': 'व्हाट्सएप के लिए विवरण कॉपी करें',
      'edit_property': 'प्रॉपर्टी विवरण संपादित करें',
      'drive_link': 'गूगल ड्राइव किराया नामा लिंक',
      'confirm_action': 'क्या आप निश्चित हैं?',
      'confirm_save_deal': 'क्या आप इन बदली हुई शर्तों को सहेजना चाहते हैं?',
      'yes': 'हाँ, सहेजें',
      'cancel': 'रद्द करें',
      'unit_label': 'इकाई संख्या/नाम (उदा. दुकान 1)',
      'floor_level': 'मंजिल (Floor)',
      'size_sqft': 'क्षेत्रफल (वर्ग फीट)',
      'business_name': 'दुकान या व्यापार का नाम',
      'business_cat': 'व्यापार श्रेणी',
      'occupant_count': 'रहने वालों की संख्या',
      'maintenance_included': 'किराये में रखरखाव शामिल है',
      'backup_db': 'संपूर्ण डेटाबेस बैकअप लें',
      'reset_pin': 'सुरक्षा पिन रीसेट करें',
      'maintenance_manager': 'शिकायत और मरम्मत प्रबंधन',
      'dispatch_notice': 'नई सूचना पत्र (Notice) जारी करें',
      'notice_title': 'सूचना का शीर्षक',
      'notice_message': 'सूचना संदेश विवरण',
      'publish_notice': 'सभी किरायेदारों को सूचना भेजें',
      'notice_published': 'सूचना सफलतापूर्वक जारी की गई',
      'dashboard': 'डैशबोर्ड अवलोकन',
      'verified_property': 'प्रमाणित प्रत्यक्ष संपत्ति',
      'report_payment': 'भुगतान की सूचना दें',
      'payment_history': 'भुगतान का इतिहास',
      'deal_summary': 'करार का विवरण',
      'maintenance': 'रखरखाव और मरम्मत',
      'notices': 'सूचना पट्ट',
      'report_sent': 'सूचना दर्ज की गई',
      'report_sent_msg': 'आपकी भुगतान सूचना पुष्टि के लिए संपत्ति के मालिक को भेज दी गई है।',
      'total_due': 'इस महीने का कुल देय',
      'amount_paid': 'भुगतान की गई राशि',
      'payment_method': 'भुगतान का माध्यम',
      'upi': 'यूपीआई (UPI)',
      'bank': 'बैंक ट्रांसफर',
      'cash': 'नकद भुगतान',
      'note_optional': 'टिप्पणी / यूटीआर संख्या (वैकल्पिक)',
      'submit_report': 'भुगतान रिपोर्ट सबमिट करें',
      'ok': 'ठीक है',
      'check_for_updates': 'ऐप अपडेट की जांच करें',
      'checking_updates': 'अपडेट की जांच हो रही है...',
      'update_available': 'नया अपडेट उपलब्ध है',
      'update_now': 'अभी अपडेट करें',
      'later': 'बाद में',
      'latest_version_msg': 'आप नवीनतम संस्करण का उपयोग कर रहे हैं!',
      'downloading_update': 'अपडेट पैकेज डाउनलोड हो रहा है...',
      'whats_new': 'नया क्या है',
      'mandatory_update': 'महत्वपूर्ण अपडेट आवश्यक है',
    },
  };

  static String tr(String key) {
    if (key == 'app_name') {
      return BrandConfig.brandName;
    }
    return _localizedValues[currentLanguage.value]?[key] ?? key;
  }
}
